pre_bump_hooks = [
    """
    sh -c '[[ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]] && echo "On branch main" || exit 1'
    """,
    "mvn package",
    "mvn versions:set -DnewVersion={{version}}",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]