pre_bump_hooks = [
    """
        sh -c "./ci/ensure_on_branch_main.sh"
    """,
    "mvn package -q",
    "mvn versions:set -DnewVersion={{version}}",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "echo {{latest}}",
]

[changelog]
remote = "github.com"
owner = "oknozor"
repository = "pokemon_api"
template = "remote"
authors = [
    { signature = "Paul Delafosse", username = "oknozor" }
]